#pragma once

#include <string>
#include <map>
#include <vector>
#include <sstream>

using namespace std;

//http://www.cplusplus.com/forum/beginner/174993/


enum DeviceType
{
	KEYBOARD = 1,
	MOUSE    = 2,
	GAMEPAD  = 3
};

enum OffSet
{
	DEVICE   = 8,
	CODE     = 16
};

#define GAMEINPUT(I) \
	I(KEYBOARD_A = KEYBOARD << DEVICE | 65 << CODE), \
	I(KEYBOARD_B = KEYBOARD << DEVICE | 66 << CODE), \
	I(KEYBOARD_C = KEYBOARD << DEVICE | 67 << CODE), \
	I(KEYBOARD_D = KEYBOARD << DEVICE | 68 << CODE), \
	I(KEYBOARD_E = KEYBOARD << DEVICE | 69 << CODE), \
	I(KEYBOARD_F = KEYBOARD << DEVICE | 70 << CODE), \
	I(KEYBOARD_G = KEYBOARD << DEVICE | 71 << CODE), \
	I(KEYBOARD_H = KEYBOARD << DEVICE | 72 << CODE), \
	I(KEYBOARD_I = KEYBOARD << DEVICE | 73 << CODE), \
	I(KEYBOARD_J = KEYBOARD << DEVICE | 74 << CODE), \
	I(KEYBOARD_K = KEYBOARD << DEVICE | 75 << CODE), \
	I(KEYBOARD_L = KEYBOARD << DEVICE | 76 << CODE), \
	I(KEYBOARD_M = KEYBOARD << DEVICE | 77 << CODE), \
	I(KEYBOARD_N = KEYBOARD << DEVICE | 78 << CODE), \
	I(KEYBOARD_O = KEYBOARD << DEVICE | 79 << CODE), \
	I(KEYBOARD_P = KEYBOARD << DEVICE | 80 << CODE), \
	I(KEYBOARD_Q = KEYBOARD << DEVICE | 81 << CODE), \
	I(KEYBOARD_R = KEYBOARD << DEVICE | 82 << CODE), \
	I(KEYBOARD_S = KEYBOARD << DEVICE | 83 << CODE), \
	I(KEYBOARD_T = KEYBOARD << DEVICE | 84 << CODE), \
	I(KEYBOARD_U = KEYBOARD << DEVICE | 85 << CODE), \
	I(KEYBOARD_V = KEYBOARD << DEVICE | 86 << CODE), \
	I(KEYBOARD_W = KEYBOARD << DEVICE | 87 << CODE), \
	I(KEYBOARD_X = KEYBOARD << DEVICE | 88 << CODE), \
	I(KEYBOARD_Y = KEYBOARD << DEVICE | 89 << CODE), \
	I(KEYBOARD_Z = KEYBOARD << DEVICE | 90 << CODE), \
													 \
	I(KEYBOARD_0 = KEYBOARD << DEVICE | 48 << CODE), \
	I(KEYBOARD_1 = KEYBOARD << DEVICE | 49 << CODE), \
	I(KEYBOARD_2 = KEYBOARD << DEVICE | 50 << CODE), \
	I(KEYBOARD_3 = KEYBOARD << DEVICE | 51 << CODE), \
	I(KEYBOARD_4 = KEYBOARD << DEVICE | 52 << CODE), \
	I(KEYBOARD_5 = KEYBOARD << DEVICE | 53 << CODE), \
	I(KEYBOARD_6 = KEYBOARD << DEVICE | 54 << CODE), \
	I(KEYBOARD_7 = KEYBOARD << DEVICE | 55 << CODE), \
	I(KEYBOARD_8 = KEYBOARD << DEVICE | 56 << CODE), \
	I(KEYBOARD_9 = KEYBOARD << DEVICE | 57 << CODE), \
	\
	I(KEYBOARD_UP = KEYBOARD << DEVICE | 265 << CODE), \
	I(KEYBOARD_DOWN = KEYBOARD << DEVICE | 264 << CODE), \
	I(KEYBOARD_LEFT = KEYBOARD << DEVICE | 263 << CODE), \
	I(KEYBOARD_RIGHT = KEYBOARD << DEVICE | 262 << CODE), \
	I(KEYBOARD_SPACE = KEYBOARD << DEVICE | 32 << CODE), \
	I(KEYBOARD_SHIFT = KEYBOARD << DEVICE | 240 << CODE), \
	\
	I(MOUSE_UP = MOUSE << DEVICE | 0 << CODE), \
	I(MOUSE_DOWN = MOUSE << DEVICE | 1 << CODE), \
	I(MOUSE_LEFT = MOUSE << DEVICE | 2 << CODE), \
	I(MOUSE_RIGHT = MOUSE << DEVICE | 3 << CODE), \
	I(MOUSE_LEFT_PRESS = MOUSE << DEVICE | 4 << CODE), \
	I(MOUSE_RIGHT_PRESS = MOUSE << DEVICE | 5 << CODE), \
	\
	I(GAMEPAD_A = GAMEPAD << DEVICE | 0 << CODE), \
	I(GAMEPAD_B = GAMEPAD << DEVICE | 1 << CODE), \
	I(GAMEPAD_X = GAMEPAD << DEVICE | 2 << CODE), \
	I(GAMEPAD_Y = GAMEPAD << DEVICE | 3 << CODE), \
	I(GAMEPAD_LB = GAMEPAD << DEVICE | 4 << CODE), \
	I(GAMEPAD_RB = GAMEPAD << DEVICE | 5 << CODE), \
	I(GAMEPAD_SELECT = GAMEPAD << DEVICE | 6 << CODE), \
	I(GAMEPAD_START = GAMEPAD << DEVICE | 7 << CODE), \
	I(GAMEPAD_L = GAMEPAD << DEVICE | 8 << CODE), \
	I(GAMEPAD_R = GAMEPAD << DEVICE | 9 << CODE), \
	I(GAMEPAD_UP = GAMEPAD << DEVICE | 10 << CODE), \
	I(GAMEPAD_RIGHT = GAMEPAD << DEVICE | 11 << CODE), \
	I(GAMEPAD_DOWN = GAMEPAD << DEVICE | 12 << CODE), \
	I(GAMEPAD_LEFT = GAMEPAD << DEVICE | 13 << CODE), \
	I(GAMEPAD_L_LEFT = GAMEPAD << DEVICE | 14 << CODE), \
	I(GAMEPAD_L_RIGHT = GAMEPAD << DEVICE | 15 << CODE), \
	I(GAMEPAD_L_DOWN = GAMEPAD << DEVICE | 16 << CODE), \
	I(GAMEPAD_L_UP = GAMEPAD << DEVICE | 17 << CODE), \
	I(GAMEPAD_LT = GAMEPAD << DEVICE | 23 << CODE), \
	I(GAMEPAD_RT = GAMEPAD << DEVICE | 25 << CODE), \
	I(GAMEPAD_R_DOWN = GAMEPAD << DEVICE | 20 << CODE), \
	I(GAMEPAD_R_UP = GAMEPAD << DEVICE | 21 << CODE), \
	I(GAMEPAD_R_LEFT = GAMEPAD << DEVICE | 18 << CODE), \
	I(GAMEPAD_R_RIGHT = GAMEPAD << DEVICE | 19 << CODE)

#define I(e) e
static enum GameInput { GAMEINPUT(I) };
#undef I

class InputConverter
{
private:

#define I(s) #s
	static vector<string> GameInputName;
#undef I

	static void FirstTimeMapSetUp();
	static map<string, int> GameInputMappings;

public:
	static GameInput StringToEnum(string input);
};