#include "InputManager.h"

#define I(s) #s
std::vector<std::string> InputConverter::GameInputName = { GAMEINPUT(I) };
#undef I

std::map<std::string, int> InputConverter::GameInputMappings = std::map<std::string, int>();

//Turns the list of string, generated by the macro list, to something readable, creating a reference code at the same time
void InputConverter::FirstTimeMapSetUp()
{
	for (int i = 0; i < GameInputName.size(); i++)
	{
		std::istringstream stream(GameInputName[i]);

		std::string inputName;
		std::string device;
		int code;
		std::string dummy;

		stream >> inputName >> dummy >> device >> dummy >> dummy >> dummy >> code >> dummy >> dummy;

		DeviceType deviceType;

		if (device == "GAMEPAD")
		{
			deviceType = GAMEPAD;
		}
		else if (device == "KEYBOARD")
		{
			deviceType = KEYBOARD;
		}
		else
		{
			deviceType = MOUSE;
		}

		int inputCode = (deviceType << DEVICE | code << CODE);

		GameInputMappings.insert(std::pair<std::string, int>(inputName, inputCode));
	}
}

//Turns string into GameInput
GameInput InputConverter::StringToEnum(const std::string & input)
{
	static bool firstTime = true;

	if (firstTime)
	{
		FirstTimeMapSetUp();
		firstTime = false;
	}

	const std::map<std::string, int>::iterator it = GameInputMappings.find(input);

	if (it != GameInputMappings.end())
	{
		return static_cast<GameInput>(it->second);
	}
}