#pragma once

enum DeviceType
{
	KEYBOARD = 0,
	MOUSE    = 1,
	GAMEPAD  = 2
};

enum OffSet
{
	DEVICE   = 0,
	CODE     = 8
};

enum GameInput
{
	KEYBOARD_A = KEYBOARD << DEVICE | 65 << CODE,
	KEYBOARD_B = KEYBOARD << DEVICE | 66 << CODE,
	KEYBOARD_C = KEYBOARD << DEVICE | 67 << CODE,
	KEYBOARD_D = KEYBOARD << DEVICE | 68 << CODE,
	KEYBOARD_E = KEYBOARD << DEVICE | 69 << CODE,
	KEYBOARD_F = KEYBOARD << DEVICE | 70 << CODE,
	KEYBOARD_G = KEYBOARD << DEVICE | 71 << CODE,
	KEYBOARD_H = KEYBOARD << DEVICE | 72 << CODE,
	KEYBOARD_I = KEYBOARD << DEVICE | 73 << CODE,
	KEYBOARD_J = KEYBOARD << DEVICE | 74 << CODE,
	KEYBOARD_K = KEYBOARD << DEVICE | 75 << CODE,
	KEYBOARD_L = KEYBOARD << DEVICE | 76 << CODE,
	KEYBOARD_M = KEYBOARD << DEVICE | 77 << CODE,
	KEYBOARD_N = KEYBOARD << DEVICE | 78 << CODE,
	KEYBOARD_O = KEYBOARD << DEVICE | 79 << CODE,
	KEYBOARD_P = KEYBOARD << DEVICE | 80 << CODE,
	KEYBOARD_Q = KEYBOARD << DEVICE | 81 << CODE,
	KEYBOARD_R = KEYBOARD << DEVICE | 82 << CODE,
	KEYBOARD_S = KEYBOARD << DEVICE | 83 << CODE,
	KEYBOARD_T = KEYBOARD << DEVICE | 84 << CODE,
	KEYBOARD_U = KEYBOARD << DEVICE | 85 << CODE,
	KEYBOARD_V = KEYBOARD << DEVICE | 86 << CODE,
	KEYBOARD_W = KEYBOARD << DEVICE | 87 << CODE,
	KEYBOARD_X = KEYBOARD << DEVICE | 88 << CODE,
	KEYBOARD_Y = KEYBOARD << DEVICE | 89 << CODE,
	KEYBOARD_Z = KEYBOARD << DEVICE | 90 << CODE,
	
	KEYBOARD_0 = KEYBOARD << DEVICE | 48 << CODE,
	KEYBOARD_1 = KEYBOARD << DEVICE | 49 << CODE,
	KEYBOARD_2 = KEYBOARD << DEVICE | 50 << CODE,
	KEYBOARD_3 = KEYBOARD << DEVICE | 51 << CODE,
	KEYBOARD_4 = KEYBOARD << DEVICE | 52 << CODE,
	KEYBOARD_5 = KEYBOARD << DEVICE | 53 << CODE,
	KEYBOARD_6 = KEYBOARD << DEVICE | 54 << CODE,
	KEYBOARD_7 = KEYBOARD << DEVICE | 55 << CODE,
	KEYBOARD_8 = KEYBOARD << DEVICE | 56 << CODE,
	KEYBOARD_9 = KEYBOARD << DEVICE | 57 << CODE,

	KEYBOARD_UP = KEYBOARD << DEVICE | 38 << CODE,
	KEYBOARD_DOWN = KEYBOARD << DEVICE | 40 << CODE,
	KEYBOARD_LEFT = KEYBOARD << DEVICE | 37 << CODE,
	KEYBOARD_RIGHT = KEYBOARD << DEVICE | 39 << CODE,
	KEYBOARD_SPACE = KEYBOARD << DEVICE | 32 << CODE,
	KEYBOARD_SHIFT = KEYBOARD << DEVICE | 16 << CODE,
	
	POINTER_UP = MOUSE << DEVICE | 0 << CODE,
	POINTER_DOWN = MOUSE << DEVICE | 1 << CODE,
	POINTER_LEFT = MOUSE << DEVICE | 2 << CODE,
	POINTER_RIGHT = MOUSE << DEVICE | 3 << CODE,
	POINTER_PRESS = MOUSE << DEVICE | 4 << CODE,
	
	GAMEPAD_A = GAMEPAD << DEVICE | 0 << CODE,
	GAMEPAD_B = GAMEPAD << DEVICE | 1 << CODE,
	GAMEPAD_X = GAMEPAD << DEVICE | 2 << CODE,
	GAMEPAD_Y = GAMEPAD << DEVICE | 3 << CODE,
	GAMEPAD_LB = GAMEPAD << DEVICE | 4 << CODE,
	GAMEPAD_RB = GAMEPAD << DEVICE | 5 << CODE,
	GAMEPAD_LT = GAMEPAD << DEVICE | 6 << CODE,
	GAMEPAD_RT = GAMEPAD << DEVICE | 7 << CODE,
	GAMEPAD_START = GAMEPAD << DEVICE | 8 << CODE,
	GAMEPAD_SELECT = GAMEPAD << DEVICE | 9 << CODE,
	GAMEPAD_L = GAMEPAD << DEVICE | 10 << CODE,
	GAMEPAD_R = GAMEPAD << DEVICE | 11 << CODE,
	GAMEPAD_UP = GAMEPAD << DEVICE | 12 << CODE,
	GAMEPAD_DOWN = GAMEPAD << DEVICE | 13 << CODE,
	GAMEPAD_LEFT = GAMEPAD << DEVICE | 14 << CODE,
	GAMEPAD_RIGHT = GAMEPAD << DEVICE | 15 << CODE,
	GAMEPAD_L_UP = GAMEPAD << DEVICE | 16 << CODE,
	GAMEPAD_L_DOWN = GAMEPAD << DEVICE | 17 << CODE,
	GAMEPAD_L_LEFT = GAMEPAD << DEVICE | 18 << CODE,
	GAMEPAD_L_RIGHT = GAMEPAD << DEVICE | 19 << CODE,
	GAMEPAD_R_UP = GAMEPAD << DEVICE | 20 << CODE,
	GAMEPAD_R_DOWN = GAMEPAD << DEVICE | 21 << CODE,
	GAMEPAD_R_LEFT = GAMEPAD << DEVICE | 22 << CODE,
	GAMEPAD_R_RIGHT = GAMEPAD << DEVICE | 23 << CODE,
};